# Generated by Django 2.0.6 on 2018-06-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
