# Generated by Django 2.0.6 on 2018-06-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180605_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='num',
            field=models.IntegerField(default=1),
        ),
    ]
