# Generated by Django 2.0.6 on 2018-06-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_vote_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
